// LOCAL HOST
### I worked on graphql so there is need of a query or something all the time to work
POST http://localhost:8000/graphql HTTP/1.1
Content-Type: application/json

{
    "query": "query { login(email:\"johndoe@gmail.com\", password:\"johndoe\") { token }}"
}

### Create an event
POST http://localhost:8000/graphql HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmFlOTc0NjRmMzM2ZjE1Y2ExZTUwZWQiLCJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwiaWF0IjoxNjU1NjE0MzU3LCJleHAiOjE2NTU2MTc5NTd9._sTvHFMeseXrhh1oIEkz9NbO1UgkxcucWQlQEXT-bLY

{
    "query": "mutation { createEvent(eventInput: {title:\"Test 1\", description:\"Visit to Italy\", price: 1599.99, date:\"2022-06-10T01:00:09.206Z\"}) {_id title } }"
}

### Get Events
POST http://localhost:8000/graphql HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmFlOTc0NjRmMzM2ZjE1Y2ExZTUwZWQiLCJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwiaWF0IjoxNjU1NjE0MzU3LCJleHAiOjE2NTU2MTc5NTd9._sTvHFMeseXrhh1oIEkz9NbO1UgkxcucWQlQEXT-bLY

{
"query": "query{ trackings { createdAt } }"
}


// HEROKU
### I worked on graphql so there is need of a query or something all the time to work
POST https://math-tracker.herokuapp.com/graphql HTTP/1.1
Content-Type: application/json

{
    "query": "query { login(email:\"carolconnel@gmail.com\", password:\"carolconnel\") { token }}"
}

### Create an event
POST https://math-tracker.herokuapp.com/graphql HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmFlYTczNGVjZWRjYWRmZjNhMThjYmEiLCJlbWFpbCI6ImNhcm9sY29ubmVsQGdtYWlsLmNvbSIsImlhdCI6MTY1NTYxMzI5NSwiZXhwIjoxNjU1NjE2ODk1fQ.ICJ4ApIA6nU7uqchIKiw1Fm1w246PURXRGIm8C87fIc

{
    "query": "mutation { createEvent(eventInput: {title:\"Test 2\", description:\"Visit to Spain\", price: 2567.95, date:\"2022-06-11T01:00:09.206Z\"}) {_id title } }"
} 
